Repository ReciHub/FunnyAlgorithms, pull requests merged in 2022-10, with the labels that each got.

#957 Added Huffman coding algorithm in C++
  Huffman Coding/huffman.cpp
Labels: hacktoberfest-accepted

#955 Added Fluery's algorithm in C++
  Fluery's Algorithm/fluery.cpp
Labels: hacktoberfest-accepted

#965 Added Kosaraju's algorithm to find Strongly Connected Components
  Kosaraju/kosaraju.cpp
Labels: hacktoberfest-accepted, Hacktoberfest2022

#969 quick sort added
  QuickSort.java
  VolumeOfCylinder/volumeOfCylinder.rb
Labels: hacktoberfest-accepted

#966 Added Aho-Corasick algorithm in CPP
  Aho-Corasick/ahocorasick.cpp
Labels: hacktoberfest-accepted, Hacktoberfest2022

#975 Create QuickSort.py
  quicksort/QuickSort.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#978 Create Bogosort.ts
  sort/bogoSort/Bogosort.ts
Labels: hacktoberfest-accepted

#984 Create anagram_checker.ts
  AnagramChecker/anagram_checker.ts
Labels: hacktoberfest-accepted

#979 Update BinarySearch.java
  Binary Search/BinarySearch.java
Labels: hacktoberfest-accepted, Hacktoberfest2022

#981 Create ArrayReverse.py
  ReverseArray-InPlace/ArrayReverse.py
Labels: Hacktoberfest, hacktoberfest-accepted

#983 Added Cyclic sort in C++
  Cyclic Sort/CyclicSort.cpp
Labels: hacktoberfest-accepted, Hacktoberfest2022

#985 Adding MonteCarlo algorithm to find pi
  MonteCarlo/monte_carlo.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#990 Removal of Duplicate codes and correction of errors
  Armstrong Numbers/ArmstrongNumber.java
  Factorial/Factorial.py
  Factorial/fact.py
  Factorial/factorial.py
  Factorial/factorial2.java
  sort/timSort/timSort.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1000 Updated Operating System directory with FCFS scheduling method
  Operating System Scheduling Algorithms/FCFS.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#997 Quick Sort in C
  quicksort/Quicksort.c
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1004 Added Shortest Remaining Time First Scheduling Algorithm in OS directory
  Operating System Scheduling Algorithms/shortest_remaining_time_first.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#953 Sliding Animated Form using HTML, CSS and JS
  sliding-form/index.html
  sliding-form/script.js
  sliding-form/style.css
  sliding-form/style.scss
Labels: Hacktoberfest, hacktoberfest-accepted, Hacktoberfest2022

#1009 Create RecursiveFibonacci.cpp
  Recursion/RecursiveFibonacci.cpp
Labels: hacktoberfest-accepted

#972 Basic AND/OR neuron
  Neuron/Main.py
  Neuron/README.md
  Neuron/TrainedNeuron.py
  Neuron/requirements.txt
Labels: hacktoberfest-accepted

#1015 Ellipse Drawing Algo in python
  Drawing Algorithm/Ellipse.py
  Drawing Algorithm/Outputs/Inputs.jpg
  Drawing Algorithm/Outputs/Inputs2.jpg
  Drawing Algorithm/Outputs/Output1.jpg
  Drawing Algorithm/Outputs/Output2.jpg
Labels: hacktoberfest-accepted

#1030 Sorting the list using insertion sort method
  Insertion sort for list/insertionSortList.cpp
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1017 Added shuffling cards in C
  DeckShuffle/deck_shuffle.c
Labels: hacktoberfest-accepted

#1038 binary search with Rubby added
  Binary Search/binary_search.rb
Labels: hacktoberfest-accepted

#1022 added optical illusion code
  optical_illusion/a.jpg
  optical_illusion/art.png
  optical_illusion/art1.png
  optical_illusion/art2.png
  optical_illusion/circle.jpg
  optical_illusion/illuNone.py
  optical_illusion/panda.png
  optical_illusion/scary.jpg
Labels: hacktoberfest-accepted

#1033 Added Patterns In CPP (continuation to pull request #1031)
  Patterns/0_and_1_pattern.cpp
  Patterns/butterfly_star_pattern.cpp
  Patterns/floyed's_triangle.cpp
  Patterns/full_pyramid.cpp
  Patterns/full_pyramid_inverse.cpp
  Patterns/half_pyramid.cpp
  Patterns/half_pyramid_using_number.cpp
  Patterns/hollow_pyramid.cpp
  Patterns/hollow_ractangle.cpp
  Patterns/inverted_half_pyramid.cpp
  Patterns/number_pyramid.cpp
  Patterns/number_pyramid_pattern.cpp
  Patterns/number_star_pattern.cpp
  Patterns/ractanguler_star_pattern.cpp
  Patterns/rhombus_pattern.cpp
  Patterns/swastic_sign_star_pattern.cpp
Labels: hacktoberfest-accepted

#954 Shell Sort Algorithm implemented in JAVA
  sort/shell/ShellSort.java
Labels: hacktoberfest-accepted

#1036 Disconnected graph bfs
  BFS/DisconnectedGraphBFS.cpp
  LongestIncreasingSubsequence/LIS.cpp
Labels: hacktoberfest-accepted

#1040 Print list of prime numbers between two numbers
  prime.py
Labels: hacktoberfest-accepted

#1037 Added algorithm Binary Search - Language RUBY and ELIXIR
  Binary Search/binary_search.ex
Labels: hacktoberfest-accepted

#1041 Create LCA of Binary tree.cpp
  BSTs/LCA of Binary tree.cpp
Labels: hacktoberfest-accepted

#1042 Create balanced parenthisis .cpp
  Balanced Paranthesis/balanced parenthisis .cpp
Labels: hacktoberfest-accepted

#1044 Create BFS.c
  BFS/BFS.c
Labels: hacktoberfest-accepted

#1008 Monte Carlo code to evaluate value of 'e'
  Financial Calculations/interest_calc.cpp
  MonteCarlo/evaluate_e.cpp
Labels: hacktoberfest-accepted

#1045 add parallax in unity script
  Unity Scripts/Environment/Parallax.cs
Labels: hacktoberfest-accepted

#1051 Create Kronecker Product
  Kronecker Product/kroneckerProduct.py
Labels: hacktoberfest-accepted

#1086 Created Perfect Number file in python
  Perfect Numbers/Perfect Number.py
Labels: hacktoberfest-accepted

#1061 This is a JavaScript function to convert an amount to coins.
  CountCoins/countCoins.js
Labels: hacktoberfest-accepted

#1066 Add right triangle checker algorithm
  Triangle Right Checker/triangle_right_checker.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1067 Add inefficient integer check algorithm
  Inefficient Integer Check/inefficient_integer_check.py
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1068 Selection Sort Using JAVA
  Selection_Sort.java
Labels: hacktoberfest-accepted, Hacktoberfest2022

#1089 Create BFS (breadth-first-search).java
  BFS/BFS (breadth-first-search).java
Labels: hacktoberfest-accepted

#1092 Add ChessFieldCounter program in CPP
  ChessFieldCounter/main.cpp
Labels: hacktoberfest-accepted

#1078 Create stack.java
  Stack/stack.java
Labels: hacktoberfest-accepted

#1093 Added World Ladder problem I and II
  Word Ladder/Word_Ladder_I.cpp
  Word Ladder/Word_Ladder_II.cpp
Labels: hacktoberfest-accepted

#1085 Add function for logical OR gate
  Boolean_Algebra/or_gate.py
Labels: hacktoberfest-accepted

#1060 Create zodiac_sign.cpp
  MontyHall/monteHall.cpp
  zodiac_sign/zodiac_sign.cpp
Labels: hacktoberfest-accepted

#1073 Added more badges to repo
  README.md
Labels: hacktoberfest-accepted

#1096 Added caesar_cipher.py an implementation with pt-br character set
  Caesar Cipher/caesar_cipher.py
Labels: hacktoberfest-accepted

#1097 Added haversini algorithm in python
  Haversini/haversini.py
Labels: hacktoberfest-accepted

#1100 created c++ version of gcd algorithm
  gcd_in_python/gcd.cpp
Labels: hacktoberfest-accepted

#1101 Create beaufort_cipher.py
  beaufort cipher/beaufort_cipher.py
Labels: hacktoberfest-accepted
